// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecondEntityFramework.DAL;

#nullable disable

namespace SecondEntityFramework.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20251229133809_StudentClassMigration")]
    partial class StudentClassMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecondEntityFramework.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("StudentAdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("StudentAdmissionDate");

                    b.Property<double>("StudentMarks")
                        .HasColumnType("float")
                        .HasColumnName("StudentMarks");

                    b.Property<string>("StudentName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StudentName");

                    b.HasKey("StudentID");

                    b.ToTable("StudentData");
                });
#pragma warning restore 612, 618
        }
    }
}
