// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSB.DAL;

#nullable disable

namespace VSB.Migrations
{
    [DbContext(typeof(VSDbUtil))]
    [Migration("20260103051147_VSMigration")]
    partial class VSMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VSB.Models.User", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UId"));

                    b.Property<string>("UserEmail")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("UserPass")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserRole")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("UId");

                    b.ToTable("UserTable");
                });
#pragma warning restore 612, 618
        }
    }
}
