// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSB.DAL;

#nullable disable

namespace VSB.Migrations
{
    [DbContext(typeof(VSDbUtil))]
    partial class VSDbUtilModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VSB.Models.User", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UId"));

                    b.Property<string>("UserEmail")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("UserPass")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserRole")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("UId");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("VSB.Models.VehicleService", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<double>("SDuration")
                        .HasColumnType("float")
                        .HasColumnName("duration");

                    b.Property<string>("SName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sname");

                    b.Property<double>("SPrice")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("SId");

                    b.ToTable("VehicleService");
                });
#pragma warning restore 612, 618
        }
    }
}
